# Ubuntu dev tools
- name: Install Ubuntu dev and common tools
  ansible.builtin.apt:
    name: 
      - build-essential
      - ninja-build
      - gettext
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - cmake
      - g++
      - unzip
      - curl
      - doxygen
  become: yes

# i3 Gaps
- name: Add the i3-Gaps release repo
  ansible.builtin.apt_repository:
    repo: 'ppa:regolith-linux/release'
    state: present
    update_cach: yes
  become: yes

- name: Install i3-gaps
  ansible.builtin.apt:
    name: i3-gaps
  become: yes

- name: Install i3 config
  copy:
    src: ./i3/config
    dest: ~/.config/i3/config
    depth: 1
# -----------------------

# i3 Blocks
- name: Get i3blocks repo
  ansible.builtin.git:
    repo: https://github.com/vivien/i3blocks
    dest: ~/workspace/repos/i3blocks
    depth: 1

- name: Run autogen for i3blocks
  command: ./autogen.sh
  args:
    chdir: ~/workspace/repos/i3blocks

- name: Run configure for i3blocks
  ansible.builtin.command: ./configure
  args:
    chdir: ~/workspace/repos/i3blocks

- name: Build i3blocks
  community.general.make:
    chdir: ~/workspace/repos/i3blocks

- name: Install i3blocks
  community.general.make:
    chdir: ~/workspace/repos/i3blocks
    target: install
  become: yes

- name: Copy i3blocks config
  copy:
    src: ./i3blocks
    dest: ~/.config/i3blocks
# -----------------------

# Alacritty
- name: Install Alacritty
  ansible.builtin.apt:
    name: alacritty
  become: yes
# -----------------------

# Zsh
- name: Install zsh
  ansible.builtin.apt:
    name: zsh
  become: yes

- name: Install om my zsh
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
    depth: 1

- name: Copy zsh config
  copy:
    src: ./zshrc
    dest: ~/.zshrc
    mode: 0644

- name: Install FIS zsh themes
  copy:
    src: ./*.zsh-theme
    dest: ~/.oh-my-zsh/custom/themes/
    depth: 1
# -----------------------

# Neovim
- name: Clone Neovim
  ansible.builtin.git:
    repo: https://github.com/neovim/neovim
    dest: ~/workspace/repos/neovim
    depth: 1

- name: Build Neovim
  community.general.make:
    chdir: ~/workspace/repos/neovim
    params:
      CMAKE_BUILD_TYPE=RelWithDebInfo

- name: Install Neovim
  community.general.make:
    chdir: ~/workspace/repos/neovim
    target: install
  become: yes

- name: Copy Neovim config
  copy:
    src: ./nvim
    dest: ~/.config/

- name: Install Neovim Packer 
  ansible.builtin.git:
    repo: https://github.com/wbthomason/packer.nvim
    dest: ~/.local/share/nvim/pack/packer/start/packer.nvim
    depth: 1

- name: Install python virtenv for Neovim
  ansible.builtin.pip:
    virtualenv: ~/.config/nvim/env3
    virtualenv_commmand: python3 -m venv

- name: Install the plugins
  ansible.builtin.command: 
    cmd: nvim --headless +plugInstall +UpdateRemotePlugins +qa

- name: Install autopep8
  ansible.builtin.pip:
    name: autopep8
    extra_args: --constraints ~/workspace/repos/m32rimm/constraints.txt
    virtualenv: ~/workspace/virtenv


