session_name: Development
start_directory: /home/noel/Projects
windows:
- window_name: Dev
  focus: True
  layout: main-vertical
  panes:
  - shell_command:
    - vim
- window_name: Command
  panes:
  - pane
- window_name: Misc
  layout: tiled
  panes:
  - pane
  - pane
  - pane
  - pane
