session_name: Development
start_directory: /home/noel/Projects
# before_script: ./some/script/name
windows:
  - window_name: Dev Window
    focus: True
    layout: main-vertical
    options:
      main-pane-width: 150
      #    shell_command_before:
      #      - '[ -d .venv -a -f .venv/bin/activate ] && source .venv/bin/activate'
    panes:
      - shell_command:
          vim
        focus: true
      - pane
      - pane
